/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Lord Nigga
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        setSize(1050, 650); // Establecer el tamaño fijo para el JFrame de ancho:1050, Alto: 650 
        setResizable(false); // Desactivar el redimensionamiento
        setLocationRelativeTo(null);// Centrar el JFrame en la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnIniciarSesion = new javax.swing.JButton();
        jtxtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jpassContraseña = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jlbfondo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIniciarSesion.setBackground(new java.awt.Color(170, 151, 98));
        btnIniciarSesion.setFont(new java.awt.Font("King Slayer", 0, 18)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(51, 51, 51));
        btnIniciarSesion.setText("Iniciar  Sesiòn");
        btnIniciarSesion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 150, 40));

        jtxtUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(170, 151, 98)));
        jtxtUsuario.setPreferredSize(new java.awt.Dimension(300, 35));
        jtxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 300, 35));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Contraseña");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 120, -1));

        jpassContraseña.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(170, 151, 98)));
        jpassContraseña.setPreferredSize(new java.awt.Dimension(300, 35));
        jpassContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpassContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(jpassContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 300, 35));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Usuario");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 70, -1));

        jlbfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/ImgLogin.jpg"))); // NOI18N
        getContentPane().add(jlbfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jpassContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpassContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpassContraseñaActionPerformed

    private void jtxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUsuarioActionPerformed
    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        GestionDatos gd = new GestionDatos();
        Login lgin = new Login();
        String jdbcUrl = "jdbc:postgresql://localhost:5432/kb_prueba";
        String usuario = "postgres";
        String password = "samuelzapatam22";
        Connection conexion;

        // Intentar establecer la conexión
        try {
            conexion = DriverManager.getConnection(jdbcUrl, usuario, password);
            System.out.println("¡Conexión exitosa!");

            // Realizar operaciones en la base de datos aquí
            GestionDatos db = new GestionDatos();
            if (jtxtUsuario.getText().length() == 0 || jpassContraseña.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "! Error no se permirten campos vacios ¡");

            } else {
                if (lgin.inicioSesionUsers(conexion, jtxtUsuario.getText(), jpassContraseña.getText()) == 1) {
                    //JOptionPane.showMessageDialog(null, "! Los datos se han ingresado correctamente ¡");
                    frmMenuAdmin x = new frmMenuAdmin();
                    x.setOnlineA(lgin.online(conexion, jtxtUsuario.getText()));
                    x.setVisible(true);
                    setVisible(false);
                    conexion.close();
                } else {

                    if (lgin.inicioSesionUsers(conexion, jtxtUsuario.getText(), jpassContraseña.getText()) == 2) {
                        //JOptionPane.showMessageDialog(null, "! Los datos se han ingresado correctamente ¡");
                        frmMenuOperador y = new frmMenuOperador();
                        y.setOnlineO(lgin.online(conexion, jtxtUsuario.getText()));
                        System.out.println(y.getOnlineO());
                        y.setVisible(true);
                        setVisible(false);
                        conexion.close();
                    } else {
                        JOptionPane.showMessageDialog(null, "! El usuario o contraseña es incorrecta ¡");
                    }
                }

            }

        } catch (SQLException e) {
            System.err.println("Error al conectar a la base de datos: " + e.getMessage());
        }


    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jlbfondo;
    private javax.swing.JPasswordField jpassContraseña;
    private javax.swing.JTextField jtxtUsuario;
    // End of variables declaration//GEN-END:variables

}
