/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Lord Nigga
 */
public class frmMenuAdmin extends javax.swing.JFrame {

    private int onlineA;

    public int getOnlineA() {
        return onlineA;
    }

    public void setOnlineA(int online) {
        this.onlineA = online;
    }

    /**
     * Creates new form frmMenuAdmin
     */
    public frmMenuAdmin() {
        initComponents();
        setSize(1050, 650); // Establecer el tamaño fijo para el JFrame de ancho:1050, Alto: 650 
        setResizable(false); // Desactivar el redimensionamiento
        setLocationRelativeTo(null);// Centrar el JFrame en la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnoperadores = new javax.swing.JButton();
        btnBarberos = new javax.swing.JButton();
        btnservicios = new javax.swing.JButton();
        btnCerrarSesionAdmin = new javax.swing.JButton();
        IconAdmin = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelAdmin = new javax.swing.JTabbedPane();
        jpnFormOpera = new javax.swing.JPanel();
        txtIdOperador = new javax.swing.JTextField();
        txtNombreOpera = new javax.swing.JTextField();
        txtTelefonoOpe = new javax.swing.JTextField();
        txtUsuarioOpera = new javax.swing.JTextField();
        pswOperadora = new javax.swing.JPasswordField();
        guardarOp = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnElimnarBarbero1 = new javax.swing.JButton();
        jblsubtNombCliente = new javax.swing.JLabel();
        jblsubtNombCliente1 = new javax.swing.JLabel();
        jblsubtNombCliente2 = new javax.swing.JLabel();
        jblsubtNombCliente3 = new javax.swing.JLabel();
        jblsubtNombCliente4 = new javax.swing.JLabel();
        iconCorona2 = new javax.swing.JLabel();
        jlbtitulo_Reservas1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        jpnFormBarbero = new javax.swing.JPanel();
        txtNombreBarber = new javax.swing.JTextField();
        btnCancelarBarbero = new javax.swing.JButton();
        jblsubtNomBarber = new javax.swing.JLabel();
        iconCorona1 = new javax.swing.JLabel();
        btnGuardaraBarbero = new javax.swing.JButton();
        btnElimnarBarbero = new javax.swing.JButton();
        txtTelefBarbero = new javax.swing.JTextField();
        jblsubtTelefBarbero = new javax.swing.JLabel();
        jblsubtIdBarbero = new javax.swing.JLabel();
        txtIdBarbero = new javax.swing.JTextField();
        jlbtitulo_Reservas = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();
        jpbFormServicios = new javax.swing.JPanel();
        txtservicio = new javax.swing.JTextField();
        txtprecioServicio = new javax.swing.JTextField();
        descripcionServicio = new javax.swing.JScrollPane();
        txtdescripcionServicio = new javax.swing.JTextArea();
        jblsubtNomBarber1 = new javax.swing.JLabel();
        jblsubtIdBarbero1 = new javax.swing.JLabel();
        jblsubtTelefBarbero1 = new javax.swing.JLabel();
        btnGuardarServicio = new javax.swing.JButton();
        btnCancelarBarbero1 = new javax.swing.JButton();
        btnElimnarBarbero2 = new javax.swing.JButton();
        jlbtitulo_Reservas2 = new javax.swing.JLabel();
        iconCorona3 = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnoperadores.setBackground(new java.awt.Color(204, 204, 204));
        btnoperadores.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        btnoperadores.setText("Operadores");
        btnoperadores.setPreferredSize(new java.awt.Dimension(140, 40));
        btnoperadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoperadoresActionPerformed(evt);
            }
        });
        jPanel1.add(btnoperadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 150, 40));

        btnBarberos.setBackground(new java.awt.Color(204, 204, 204));
        btnBarberos.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        btnBarberos.setText("Barberos");
        btnBarberos.setPreferredSize(new java.awt.Dimension(140, 40));
        btnBarberos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarberosActionPerformed(evt);
            }
        });
        jPanel1.add(btnBarberos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 150, 40));

        btnservicios.setBackground(new java.awt.Color(204, 204, 204));
        btnservicios.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        btnservicios.setText("Servicios");
        btnservicios.setPreferredSize(new java.awt.Dimension(140, 40));
        btnservicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnserviciosActionPerformed(evt);
            }
        });
        jPanel1.add(btnservicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 150, 40));

        btnCerrarSesionAdmin.setBackground(new java.awt.Color(210, 187, 118));
        btnCerrarSesionAdmin.setFont(new java.awt.Font("Gadugi", 1, 15)); // NOI18N
        btnCerrarSesionAdmin.setForeground(new java.awt.Color(204, 0, 51));
        btnCerrarSesionAdmin.setText("Cerrar Sesion");
        btnCerrarSesionAdmin.setBorder(null);
        btnCerrarSesionAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrarSesionAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrarSesionAdmin.setPreferredSize(new java.awt.Dimension(116, 26));
        btnCerrarSesionAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarSesionAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 560, 120, 40));

        IconAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Admin.png"))); // NOI18N
        jPanel1.add(IconAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/fonddoMenuOpe.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, -30, 490, 680));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 650));

        jpnFormOpera.setBackground(new java.awt.Color(255, 204, 255));
        jpnFormOpera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdOperadorActionPerformed(evt);
            }
        });
        jpnFormOpera.add(txtIdOperador, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 201, 234, 36));

        txtNombreOpera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreOperaActionPerformed(evt);
            }
        });
        jpnFormOpera.add(txtNombreOpera, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 201, 234, 36));
        jpnFormOpera.add(txtTelefonoOpe, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 290, 234, 36));
        jpnFormOpera.add(txtUsuarioOpera, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 290, 234, 36));
        jpnFormOpera.add(pswOperadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 376, 234, 36));

        guardarOp.setBackground(new java.awt.Color(210, 187, 118));
        guardarOp.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        guardarOp.setText("Guardar");
        guardarOp.setToolTipText("");
        guardarOp.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.green, java.awt.Color.green));
        guardarOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarOpActionPerformed(evt);
            }
        });
        jpnFormOpera.add(guardarOp, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, 150, 40));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(210, 187, 118));
        jButton2.setText("Cancelar");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 51), new java.awt.Color(204, 0, 51)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jpnFormOpera.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 150, 40));

        btnElimnarBarbero1.setBackground(new java.awt.Color(210, 187, 118));
        btnElimnarBarbero1.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        btnElimnarBarbero1.setText("Eliminar");
        btnElimnarBarbero1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 0), new java.awt.Color(255, 153, 0)));
        jpnFormOpera.add(btnElimnarBarbero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, 150, 40));

        jblsubtNombCliente.setFont(new java.awt.Font("Gadugi", 1, 19)); // NOI18N
        jblsubtNombCliente.setForeground(new java.awt.Color(255, 255, 255));
        jblsubtNombCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jblsubtNombCliente.setText("Nombre");
        jpnFormOpera.add(jblsubtNombCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        jblsubtNombCliente1.setFont(new java.awt.Font("Gadugi", 1, 19)); // NOI18N
        jblsubtNombCliente1.setForeground(new java.awt.Color(255, 255, 255));
        jblsubtNombCliente1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jblsubtNombCliente1.setText("Cedula Operador");
        jpnFormOpera.add(jblsubtNombCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jblsubtNombCliente2.setFont(new java.awt.Font("Gadugi", 1, 19)); // NOI18N
        jblsubtNombCliente2.setForeground(new java.awt.Color(255, 255, 255));
        jblsubtNombCliente2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jblsubtNombCliente2.setText("Telefono");
        jpnFormOpera.add(jblsubtNombCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        jblsubtNombCliente3.setFont(new java.awt.Font("Gadugi", 1, 19)); // NOI18N
        jblsubtNombCliente3.setForeground(new java.awt.Color(255, 255, 255));
        jblsubtNombCliente3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jblsubtNombCliente3.setText("Usuario");
        jpnFormOpera.add(jblsubtNombCliente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        jblsubtNombCliente4.setFont(new java.awt.Font("Gadugi", 1, 19)); // NOI18N
        jblsubtNombCliente4.setForeground(new java.awt.Color(255, 255, 255));
        jblsubtNombCliente4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jblsubtNombCliente4.setText("Contraseña");
        jpnFormOpera.add(jblsubtNombCliente4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        iconCorona2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconCorona2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Corona Negra.png"))); // NOI18N
        jpnFormOpera.add(iconCorona2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 110, 80));

        jlbtitulo_Reservas1.setBackground(new java.awt.Color(102, 102, 102));
        jlbtitulo_Reservas1.setFont(new java.awt.Font("King Slayer", 2, 48)); // NOI18N
        jlbtitulo_Reservas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbtitulo_Reservas1.setText("GESTION  OPERADOR");
        jpnFormOpera.add(jlbtitulo_Reservas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 580, 60));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/fonddoMenuOpe2.png"))); // NOI18N
        jpnFormOpera.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-450, -20, 1260, 690));

        panelAdmin.addTab("Reportes", jpnFormOpera);

        jpnFormBarbero.setBackground(new java.awt.Color(102, 0, 102));
        jpnFormBarbero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombreBarber.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        txtNombreBarber.setToolTipText("");
        jpnFormBarbero.add(txtNombreBarber, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 332, 35));

        btnCancelarBarbero.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelarBarbero.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        btnCancelarBarbero.setForeground(new java.awt.Color(210, 187, 118));
        btnCancelarBarbero.setText("Cancelar");
        btnCancelarBarbero.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 51), new java.awt.Color(204, 0, 51)));
        btnCancelarBarbero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarBarberoActionPerformed(evt);
            }
        });
        jpnFormBarbero.add(btnCancelarBarbero, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 150, 40));

        jblsubtNomBarber.setFont(new java.awt.Font("Gadugi", 1, 19)); // NOI18N
        jblsubtNomBarber.setForeground(new java.awt.Color(255, 255, 255));
        jblsubtNomBarber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jblsubtNomBarber.setText("Nombre");
        jpnFormBarbero.add(jblsubtNomBarber, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        iconCorona1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconCorona1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Corona Negra.png"))); // NOI18N
        jpnFormBarbero.add(iconCorona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 110, 80));

        btnGuardaraBarbero.setBackground(new java.awt.Color(210, 187, 118));
        btnGuardaraBarbero.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        btnGuardaraBarbero.setText("Guardar");
        btnGuardaraBarbero.setToolTipText("");
        btnGuardaraBarbero.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 0), java.awt.Color.green));
        btnGuardaraBarbero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardaraBarberoActionPerformed(evt);
            }
        });
        jpnFormBarbero.add(btnGuardaraBarbero, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, 150, 40));

        btnElimnarBarbero.setBackground(new java.awt.Color(210, 187, 118));
        btnElimnarBarbero.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        btnElimnarBarbero.setText("Eliminar");
        btnElimnarBarbero.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 0), new java.awt.Color(255, 153, 0)));
        jpnFormBarbero.add(btnElimnarBarbero, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 150, 40));

        txtTelefBarbero.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        txtTelefBarbero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefBarberoActionPerformed(evt);
            }
        });
        jpnFormBarbero.add(txtTelefBarbero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 235, 35));

        jblsubtTelefBarbero.setFont(new java.awt.Font("Gadugi", 1, 19)); // NOI18N
        jblsubtTelefBarbero.setForeground(new java.awt.Color(255, 255, 255));
        jblsubtTelefBarbero.setText("Telefono");
        jpnFormBarbero.add(jblsubtTelefBarbero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        jblsubtIdBarbero.setFont(new java.awt.Font("Gadugi", 1, 19)); // NOI18N
        jblsubtIdBarbero.setForeground(new java.awt.Color(255, 255, 255));
        jblsubtIdBarbero.setText("Cedula Barbero");
        jpnFormBarbero.add(jblsubtIdBarbero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        txtIdBarbero.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jpnFormBarbero.add(txtIdBarbero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 235, 35));

        jlbtitulo_Reservas.setBackground(new java.awt.Color(102, 102, 102));
        jlbtitulo_Reservas.setFont(new java.awt.Font("King Slayer", 2, 48)); // NOI18N
        jlbtitulo_Reservas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbtitulo_Reservas.setText("GESTION BARBEROS");
        jpnFormBarbero.add(jlbtitulo_Reservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 500, 60));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/fonddoMenuOpe2.png"))); // NOI18N
        jpnFormBarbero.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-450, -20, 1260, 690));

        panelAdmin.addTab("Operadores", jpnFormBarbero);

        jpbFormServicios.setBackground(new java.awt.Color(0, 153, 153));
        jpbFormServicios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtservicio.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        txtservicio.setCaretColor(new java.awt.Color(255, 255, 255));
        txtservicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtservicioActionPerformed(evt);
            }
        });
        jpbFormServicios.add(txtservicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 235, 35));

        txtprecioServicio.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        txtprecioServicio.setToolTipText("");
        jpbFormServicios.add(txtprecioServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 332, 35));

        txtdescripcionServicio.setColumns(20);
        txtdescripcionServicio.setRows(5);
        descripcionServicio.setViewportView(txtdescripcionServicio);

        jpbFormServicios.add(descripcionServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 600, 70));

        jblsubtNomBarber1.setFont(new java.awt.Font("Gadugi", 1, 19)); // NOI18N
        jblsubtNomBarber1.setForeground(new java.awt.Color(255, 255, 255));
        jblsubtNomBarber1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jblsubtNomBarber1.setText("Precio");
        jpbFormServicios.add(jblsubtNomBarber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        jblsubtIdBarbero1.setFont(new java.awt.Font("Gadugi", 1, 19)); // NOI18N
        jblsubtIdBarbero1.setForeground(new java.awt.Color(255, 255, 255));
        jblsubtIdBarbero1.setText("Nombre Servicio");
        jpbFormServicios.add(jblsubtIdBarbero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jblsubtTelefBarbero1.setFont(new java.awt.Font("Gadugi", 1, 19)); // NOI18N
        jblsubtTelefBarbero1.setForeground(new java.awt.Color(255, 255, 255));
        jblsubtTelefBarbero1.setText("Descripcion");
        jpbFormServicios.add(jblsubtTelefBarbero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        btnGuardarServicio.setBackground(new java.awt.Color(210, 187, 118));
        btnGuardarServicio.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        btnGuardarServicio.setText("Guardar");
        btnGuardarServicio.setToolTipText("");
        btnGuardarServicio.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 0), java.awt.Color.green));
        btnGuardarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarServicioActionPerformed(evt);
            }
        });
        jpbFormServicios.add(btnGuardarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, 150, 40));

        btnCancelarBarbero1.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelarBarbero1.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        btnCancelarBarbero1.setForeground(new java.awt.Color(210, 187, 118));
        btnCancelarBarbero1.setText("Cancelar");
        btnCancelarBarbero1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 51), new java.awt.Color(204, 0, 51)));
        btnCancelarBarbero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarBarbero1ActionPerformed(evt);
            }
        });
        jpbFormServicios.add(btnCancelarBarbero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 150, 40));

        btnElimnarBarbero2.setBackground(new java.awt.Color(210, 187, 118));
        btnElimnarBarbero2.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        btnElimnarBarbero2.setText("Eliminar");
        btnElimnarBarbero2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 0), new java.awt.Color(255, 153, 0)));
        jpbFormServicios.add(btnElimnarBarbero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 150, 40));

        jlbtitulo_Reservas2.setBackground(new java.awt.Color(102, 102, 102));
        jlbtitulo_Reservas2.setFont(new java.awt.Font("King Slayer", 2, 48)); // NOI18N
        jlbtitulo_Reservas2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbtitulo_Reservas2.setText("GESTION SERVICIOS");
        jpbFormServicios.add(jlbtitulo_Reservas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 520, 60));

        iconCorona3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconCorona3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Corona Negra.png"))); // NOI18N
        jpbFormServicios.add(iconCorona3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 110, 80));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/fonddoMenuOpe2.png"))); // NOI18N
        jpbFormServicios.add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-450, -20, 1260, 690));

        panelAdmin.addTab("Barberos", jpbFormServicios);

        getContentPane().add(panelAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, -36, 780, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionAdminActionPerformed
        // Mostrar un cuadro de diálogo de confirmación personalizado
        String[] options = {"Cancelar", "Cerrar"};
        int choice = JOptionPane.showOptionDialog(this, "¿Seguro que deseas cerrar sesión?", "Confirmación", 0, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

        if (choice == 1) {
            // Si elige "Cerrar", cierra la ventana actual
            this.dispose();
            // Abre la ventana de inicio de sesión (frmLogin)
            frmLogin loginForm = new frmLogin();
            loginForm.setVisible(true);
        }
    }//GEN-LAST:event_btnCerrarSesionAdminActionPerformed

    private void btnoperadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoperadoresActionPerformed
        // TODO add your handling code here:
        panelAdmin.setSelectedIndex(0);
    }//GEN-LAST:event_btnoperadoresActionPerformed

    private void btnBarberosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarberosActionPerformed
        // TODO add your handling code here:
        panelAdmin.setSelectedIndex(1);
    }//GEN-LAST:event_btnBarberosActionPerformed

    private void btnserviciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnserviciosActionPerformed
        // TODO add your handling code here:
        panelAdmin.setSelectedIndex(2);
    }//GEN-LAST:event_btnserviciosActionPerformed

    private void txtTelefBarberoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefBarberoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefBarberoActionPerformed

//barberos
    private void btnGuardaraBarberoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardaraBarberoActionPerformed
        //Guardar barbero Admin

        String idBarbero = txtIdBarbero.getText();
        String nombreBarbero = txtNombreBarber.getText();
        String telefonoBarbero = txtTelefBarbero.getText();
        GestionDatos cbarber = new GestionDatos();

        boolean barValido = true;
        // Verificar que los campos no estén vacíos
        if (idBarbero.trim().isEmpty() || nombreBarbero.trim().isEmpty() || telefonoBarbero.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos deben ser completados", "Error", JOptionPane.ERROR_MESSAGE);
            barValido = false;
            return; // Detener el proceso de guardado si algún campo está vacío
        }

        // Validar longitud y contenido numérico si es necesario
        if (idBarbero.length() < 8 || idBarbero.length() > 15) {
            JOptionPane.showMessageDialog(this, "El ID del barbero debe tener entre 8 y 15 caracteres", "Error", JOptionPane.ERROR_MESSAGE);
            barValido = false;
            return; // Detener el proceso de guardado si la longitud del ID no está en el rango especificado
        }

        try {
            int id = Integer.parseInt(idBarbero);
            // Puedes realizar más validaciones específicas aquí si es necesario
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID del barbero debe ser un valor numérico", "Error", JOptionPane.ERROR_MESSAGE);
            barValido = false;
            return; // Detener el proceso de guardado si el ID no es numérico
        }

        if (telefonoBarbero.length() != 10) {
            JOptionPane.showMessageDialog(this, "El teléfono del barbero debe tener exactamente 10 caracteres", "Error", JOptionPane.ERROR_MESSAGE);
            barValido = false;
            return; // Detener el proceso de guardado si la longitud del teléfono no es 10
        }

        try {
            Long.parseLong(telefonoBarbero); // Intentar convertir a número, no se usa el valor devuelto porque solo se necesita verificar si es numérico
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El teléfono del barbero debe ser un valor numérico", "Error", JOptionPane.ERROR_MESSAGE);
            barValido = false;
            return; // Detener el proceso de guardado si el teléfono no es numérico
        }

        // Si todas las validaciones pasan, puedes proceder con el proceso de guardado
        // agregar el código para guardar la información en tu base de datos o hacer lo que sea necesario
        JOptionPane.showMessageDialog(this, "Barbero guardado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        if (barValido) {
            Barbero barber = new Barbero();
            barber.setNombre(nombreBarbero);
            barber.setId(idBarbero);
            barber.setTelefono(telefonoBarbero);
            String jdbcUrl = "jdbc:postgresql://localhost:5432/kings_barbershop";
            String usuario = "postgres";
            String contraseña = "samuelzapatam22";

            // Intentar establecer la conexión
            try {
                Connection conexion = DriverManager.getConnection(jdbcUrl, usuario, contraseña);
                System.out.println("¡Conexión exitosa!");
                cbarber.insertarDatosBarbers(conexion, nombreBarbero, idBarbero, telefonoBarbero);
            } catch (SQLException ex) {
                Logger.getLogger(frmMenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        // Limpiar los campos después del registro
        txtIdBarbero.setText("");
        txtNombreBarber.setText("");
        txtTelefBarbero.setText("");
    }//GEN-LAST:event_btnGuardaraBarberoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Establecer los campos en blanco
        txtIdOperador.setText("");
        txtNombreOpera.setText("");
        txtTelefonoOpe.setText("");
        txtUsuarioOpera.setText("");
        pswOperadora.setText(""); // También puedes establecer el campo de contraseña en blanco
        JOptionPane.showMessageDialog(this, "Se cancelo registro Operador", "Información", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnCancelarBarberoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBarberoActionPerformed
        // Establecer los campos en blanco
        txtIdBarbero.setText("");
        txtNombreBarber.setText("");
        txtTelefBarbero.setText("");

        JOptionPane.showMessageDialog(this, "Se cancelo registro Barbero", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnCancelarBarberoActionPerformed

    private void btnGuardarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarServicioActionPerformed
        String nombreServicio = txtservicio.getText();
        float precio = Float.parseFloat(txtprecioServicio.getText());
        String descripcion = txtdescripcionServicio.getText();

        GestionDatos cS = new GestionDatos();

        boolean serValido = true;
        // Verificar que los campos no estén vacíos
        if (nombreServicio.trim().isEmpty() || descripcion.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos deben ser completados", "Error", JOptionPane.ERROR_MESSAGE);
            serValido = false;
            return; // Detener el proceso de guardado si algún campo está vacío
        }

        // Validar longitud y contenido numérico si es necesario
        // Si todas las validaciones pasan, puedes proceder con el proceso de guardado
        // agregar el código para guardar la información en tu base de datos o hacer lo que sea necesario
        JOptionPane.showMessageDialog(this, "Servicio guardado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        if (serValido) {

            String jdbcUrl = "jdbc:postgresql://localhost:5432/kings_barbershop";
            String usuario = "postgres";
            String contraseña = "samuelzapatam22";

            // Intentar establecer la conexión
            try {
                Connection conexion = DriverManager.getConnection(jdbcUrl, usuario, contraseña);
                System.out.println("¡Conexión exitosa!");
                cS.insertarServices(conexion, nombreServicio, precio, descripcion);
            } catch (SQLException ex) {
                Logger.getLogger(frmMenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        // Limpiar los campos después del registro
        txtservicio.setText("");
        txtprecioServicio.setText("");
        txtdescripcionServicio.setText("");


    }//GEN-LAST:event_btnGuardarServicioActionPerformed

    private void btnCancelarBarbero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBarbero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarBarbero1ActionPerformed

    private void txtIdOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdOperadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdOperadorActionPerformed

    private void txtNombreOperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreOperaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreOperaActionPerformed

    private void guardarOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarOpActionPerformed
        String idOperador = txtIdOperador.getText();
        String nombreOperador = txtNombreOpera.getText();
        String telefonoOperador = txtTelefonoOpe.getText();
        String usuarioOperador = txtUsuarioOpera.getText();
        String contraseñaOperador = pswOperadora.getText();

        GestionDatos cOp = new GestionDatos();

        boolean opValido = true;
        // Verificar que los campos no estén vacíos
        if (idOperador.trim().isEmpty() || nombreOperador.trim().isEmpty() || telefonoOperador.trim().isEmpty() || usuarioOperador.trim().isEmpty() || contraseñaOperador.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos deben ser completados", "Error", JOptionPane.ERROR_MESSAGE);
            opValido = false;
            return; // Detener el proceso de guardado si algún campo está vacío
        }

        // Validar longitud y contenido numérico si es necesario
        if (idOperador.length() < 8 || idOperador.length() > 15) {
            JOptionPane.showMessageDialog(this, "El ID del operador debe tener entre 8 y 15 caracteres", "Error", JOptionPane.ERROR_MESSAGE);
            opValido = false;
            return; // Detener el proceso de guardado si la longitud del ID no está en el rango especificado
        }

        try {
            int id = Integer.parseInt(idOperador);
            // Puedes realizar más validaciones específicas aquí si es necesario
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID del operador debe ser un valor numérico", "Error", JOptionPane.ERROR_MESSAGE);
            opValido = false;
            return; // Detener el proceso de guardado si el ID no es numérico
        }

        if (telefonoOperador.length() != 10) {
            JOptionPane.showMessageDialog(this, "El teléfono del operador debe tener exactamente 10 caracteres", "Error", JOptionPane.ERROR_MESSAGE);
            opValido = false;
            return; // Detener el proceso de guardado si la longitud del teléfono no es 10
        }

        try {
            Long.parseLong(telefonoOperador); // Intentar convertir a número, no se usa el valor devuelto porque solo se necesita verificar si es numérico
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El teléfono del operador debe ser un valor numérico", "Error", JOptionPane.ERROR_MESSAGE);
            opValido = false;
            return; // Detener el proceso de guardado si el teléfono no es numérico
        }

        // Si todas las validaciones pasan, puedes proceder con el proceso de guardado
        // agregar el código para guardar la información en tu base de datos o hacer lo que sea necesario
        JOptionPane.showMessageDialog(this, "operador guardado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        if (opValido) {
            Operador op = new Operador();
            op.setNombre(nombreOperador);
            op.setId(idOperador);
            op.setTelefono(telefonoOperador);
            String jdbcUrl = "jdbc:postgresql://localhost:5432/kings_barbershop";
            String usuario = "postgres";
            String contraseña = "samuelzapatam22";

            // Intentar establecer la conexión
            try {
                Connection conexionOp = DriverManager.getConnection(jdbcUrl, usuario, contraseña);
                System.out.println("¡Conexión exitosa!");
                cOp.insertarDatosUsers(conexionOp, nombreOperador, idOperador, telefonoOperador, usuarioOperador, contraseñaOperador);
            } catch (SQLException ex) {
                Logger.getLogger(frmMenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        // Limpiar los campos después del registro
        txtIdOperador.setText("");
        txtNombreOpera.setText("");
        txtTelefonoOpe.setText("");
        txtUsuarioOpera.setText("");
        pswOperadora.setText("");
       

    }//GEN-LAST:event_guardarOpActionPerformed

    private void txtservicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtservicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtservicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuAdmin().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconAdmin;
    private javax.swing.JButton btnBarberos;
    private javax.swing.JButton btnCancelarBarbero;
    private javax.swing.JButton btnCancelarBarbero1;
    private javax.swing.JButton btnCerrarSesionAdmin;
    private javax.swing.JButton btnElimnarBarbero;
    private javax.swing.JButton btnElimnarBarbero1;
    private javax.swing.JButton btnElimnarBarbero2;
    private javax.swing.JButton btnGuardarServicio;
    private javax.swing.JButton btnGuardaraBarbero;
    private javax.swing.JButton btnoperadores;
    private javax.swing.JButton btnservicios;
    private javax.swing.JScrollPane descripcionServicio;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JButton guardarOp;
    private javax.swing.JLabel iconCorona1;
    private javax.swing.JLabel iconCorona2;
    private javax.swing.JLabel iconCorona3;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jblsubtIdBarbero;
    private javax.swing.JLabel jblsubtIdBarbero1;
    private javax.swing.JLabel jblsubtNomBarber;
    private javax.swing.JLabel jblsubtNomBarber1;
    private javax.swing.JLabel jblsubtNombCliente;
    private javax.swing.JLabel jblsubtNombCliente1;
    private javax.swing.JLabel jblsubtNombCliente2;
    private javax.swing.JLabel jblsubtNombCliente3;
    private javax.swing.JLabel jblsubtNombCliente4;
    private javax.swing.JLabel jblsubtTelefBarbero;
    private javax.swing.JLabel jblsubtTelefBarbero1;
    private javax.swing.JLabel jlbtitulo_Reservas;
    private javax.swing.JLabel jlbtitulo_Reservas1;
    private javax.swing.JLabel jlbtitulo_Reservas2;
    private javax.swing.JPanel jpbFormServicios;
    private javax.swing.JPanel jpnFormBarbero;
    private javax.swing.JPanel jpnFormOpera;
    private javax.swing.JTabbedPane panelAdmin;
    private javax.swing.JPasswordField pswOperadora;
    private javax.swing.JTextField txtIdBarbero;
    private javax.swing.JTextField txtIdOperador;
    private javax.swing.JTextField txtNombreBarber;
    private javax.swing.JTextField txtNombreOpera;
    private javax.swing.JTextField txtTelefBarbero;
    private javax.swing.JTextField txtTelefonoOpe;
    private javax.swing.JTextField txtUsuarioOpera;
    private javax.swing.JTextArea txtdescripcionServicio;
    private javax.swing.JTextField txtprecioServicio;
    private javax.swing.JTextField txtservicio;
    // End of variables declaration//GEN-END:variables
}
